package com.example.provider.contract;

import com.example.provider.GreetingController;
import io.restassured.module.mockmvc.RestAssuredMockMvc;
import org.junit.jupiter.api.BeforeEach;

/**
 * Base class for the tests generated by Spring Cloud Contract from the
 * Groovy contracts under {@code src/test/resources/contracts}.
 *
 * <p>Configured via {@code baseClassForTests} in the pom's
 * spring-cloud-contract-maven-plugin. We use RestAssured MockMvc in
 * standalone mode so contract verification does not need a running server.
 */
public abstract class ContractVerifierBase {

    @BeforeEach
    void setup() {
        RestAssuredMockMvc.standaloneSetup(new GreetingController());
    }
}
